### ISSUE TITLE
每个函数没有判断输入指针是否为空指针

### ISSUE THREAD

**Issue by Ynghhhhhhhhh** [2223791042/List#1]
void ListInit(struct List *list)
{
    struct Node *node = (struct Node *)malloc(sizeof(struct Node));
    if (node == NULL) {
        return;
    }

    node->next = node;
    node->prev = node;
    list->base = node;
    list->size = 0;
}
例如此处，如果list==NULL，程序运行道list->base处会崩溃

**Comment by 2223791042** [comment]
### 谢谢提出，目前 Bug 已经修复完毕
欢迎继续探讨交流！(●'◡'●)
